export interface Project {
  id: number;
  slug: string;
  name: string;
  tag: string;
  desc: string;
  bg: string;
  accent: string;
  textColor: string;
  caseStudyTheme: 'dark' | 'light';
  year: string;
  client: string;
  services: string[];
  challenge: string;
  solution: string;
  results: { label: string; value: string }[];
  mockupBg: string;
  url?: string;
  image: string;
  fullImage?: string;
}

export const PROJECTS: Project[] = [
  {
    id: 106,
    slug: 'theunknownband',
    name: 'The Unknown Band',
    tag: 'Web · Music',
    desc: 'An electrifying digital presence and touring schedule for an emerging rock band.',
    bg: '#000000',
    accent: '#10b981',
    textColor: 'text-zinc-100',
    caseStudyTheme: 'dark',
    year: '2023',
    client: 'The Unknown Band',
    services: ['Web Design', 'Audio Integration', 'Tour Management Setup'],
    challenge: 'The band needed a centralized hub to host their unreleased tracks, showcase high-octane tour photography, and sell merchandise directly to fans without relying solely on social media algorithms.',
    solution: 'We crafted a moody, high-energy website featuring a custom audio player, immersive full-screen video backgrounds, and a seamless Shopify integration for instant merch drops.',
    results: [
      { label: 'Merch Sales', value: '+85%' },
      { label: 'Stream Clicks', value: '12k' },
      { label: 'Load Time', value: '1.2s' },
    ],
    mockupBg: 'bg-zinc-950',
    url: 'https://theunknownband.netlify.app/',
    image: '/projects/theunknownband-main.png',
    fullImage: '/projects/theunknownband-full.png',
  },
  {
    id: 105,
    slug: 'devshelter',
    name: 'DevShelter',
    tag: 'Web · Tooling',
    desc: 'A comprehensive resource directory and community hub for developers.',
    bg: '#0f172a',
    accent: '#8b5cf6',
    textColor: 'text-violet-100',
    caseStudyTheme: 'dark',
    year: '2023',
    client: 'DevShelter',
    services: ['Web App Development', 'Database Architecture', 'UI Design'],
    challenge: 'Developers constantly struggle to find reliable tools and resources scattered across the internet. DevShelter needed a unified, searchable, and highly categorized platform.',
    solution: 'We built a lightning-fast React application with advanced filtering capabilities, a sleek dark-mode interface, and a robust backend to handle thousands of community submissions.',
    results: [
      { label: 'Daily Active Users', value: '5k+' },
      { label: 'Search Speed', value: '<50ms' },
      { label: 'Community Submissions', value: '1.2k' },
    ],
    mockupBg: 'bg-slate-900',
    url: 'https://devshelter.vercel.app/',
    image: '/projects/devshelter.jpg',
  },
  {
    id: 103,
    slug: 'fragilebase',
    name: 'Fragilebase',
    tag: 'Web · Agency',
    desc: 'A striking digital portfolio for a creative design agency.',
    bg: '#0f172a',
    accent: '#3b82f6',
    textColor: 'text-blue-100',
    caseStudyTheme: 'dark',
    year: '2024',
    client: 'Fragilebase',
    services: ['Web Design', 'UI/UX', 'Frontend Development'],
    challenge: 'Fragilebase required a portfolio that didn\'t just display their work, but framed it as art, with complex animations and seamless page transitions.',
    solution: 'We engineered a highly interactive Next.js application with bespoke WebGL implementations to bring their 3D design concepts into an immersive, fluid browser experience.',
    results: [
      { label: 'Engagement Time', value: '3m+' },
      { label: 'Bounce Rate', value: '<20%' },
      { label: 'Client Inquiries', value: '2x' },
    ],
    mockupBg: 'bg-slate-900',
    url: 'https://fragilebase.com/',
    image: '/projects/fragilebase.jpg',
  },
  {
    id: 104,
    slug: 'apexgum',
    name: 'Apex Gum',
    tag: 'Web · E-commerce',
    desc: 'An energetic, high-performance storefront for an extreme energy gum brand.',
    bg: '#18181b',
    accent: '#ef4444',
    textColor: 'text-red-50',
    caseStudyTheme: 'dark',
    year: '2024',
    client: 'Apex Gum',
    services: ['E-commerce', 'Brand Identity', 'Frontend Build'],
    challenge: 'Apex Gum needed an aggressively bold e-commerce experience to capture the attention of athletes and gamers with extremely short attention spans.',
    solution: 'We deployed a brutally fast storefront using a highly optimized frontend paired with Shopify\'s Storefront API, featuring bold typography, dark aesthetics, and rapid checkout flows.',
    results: [
      { label: 'Conversion Rate', value: '4.2%' },
      { label: 'Load Speed', value: '0.6s' },
      { label: 'Mobile Sales', value: '80%' },
    ],
    mockupBg: 'bg-zinc-950',
    url: 'https://apexgum.com/',
    image: '/projects/apexgum.jpg',
  },
  {
    id: 101,
    slug: 'chaat-lounge',
    name: 'Chaat Lounge',
    tag: 'Web · Food & Beverage',
    desc: 'A vibrant, mouth-watering digital experience for a modern Indian street food brand.',
    bg: '#fdf2f8',
    accent: '#ec4899',
    textColor: 'text-pink-950',
    caseStudyTheme: 'light',
    year: '2024',
    client: 'Chaat Lounge',
    services: ['Web Design', 'Next.js Development', 'Menu Integration'],
    challenge: 'Chaat Lounge needed an online presence that matched the vibrant, energetic, and colorful nature of their street food, while making it incredibly easy for customers to view the menu and find locations.',
    solution: 'We designed a highly visual, fast-loading website using Next.js with rich imagery, vibrant color transitions, and an optimized mobile menu experience tailored for hungry customers on the go.',
    results: [
      { label: 'Mobile Traffic', value: '75%' },
      { label: 'Menu Views', value: '+140%' },
      { label: 'Load Time', value: '<1s' },
    ],
    mockupBg: 'bg-pink-50',
    url: 'https://chaat-lounge.vercel.app/',
    image: '/projects/chaat-lounge.jpg',
  },
  {
    id: 102,
    slug: 'mittron-icecream',
    name: 'Mittron Ice Cream',
    tag: 'Web · Retail',
    desc: 'A delightfully sweet e-commerce and brand showcase for an artisanal ice cream parlor.',
    bg: '#fefce8',
    accent: '#eab308',
    textColor: 'text-yellow-950',
    caseStudyTheme: 'light',
    year: '2024',
    client: 'Mittron Ice Cream',
    services: ['Brand Strategy', 'UI/UX Design', 'Web Development'],
    challenge: 'The brand needed to communicate their artisanal quality and unique flavor combinations online to drive both foot traffic to their parlors and online delivery orders.',
    solution: 'We built a delightful web experience featuring smooth, creamy animations, high-quality product photography, and a seamless ordering integration to drive local sales.',
    results: [
      { label: 'Online Orders', value: '+60%' },
      { label: 'Bounce Rate', value: '-22%' },
      { label: 'Brand Lift', value: 'High' },
    ],
    mockupBg: 'bg-yellow-50',
    url: 'https://mittron-icecream.vercel.app/',
    image: '/projects/mittron-icecream.jpg',
  },
  {
    id: 1,
    slug: 'thepiecraft-marketing',
    name: 'ThePieCraft Marketing',
    tag: 'Web · Brand',
    desc: 'The global marketing face of ThePieCraft web design & development agency.',
    bg: '#f0ece1',
    accent: '#000000',
    textColor: 'text-black',
    caseStudyTheme: 'light',
    year: '2024',
    client: 'ThePieCraft',
    services: ['Brand Strategy', 'UI/UX Design', 'Next.js Development'],
    challenge: 'As a rapidly growing agency, we needed a marketing website that reflected our high standard of design and technical excellence to attract premium enterprise and mid-market clients.',
    solution: 'We built a lightning-fast, highly aesthetic web experience featuring smooth scroll mechanics, dynamic dark/light mode themes, and cinematic micro-interactions using Next.js and Framer Motion.',
    results: [
      { label: 'Performance', value: '100' },
      { label: 'Load Time', value: '<1s' },
      { label: 'Conversion', value: '+35%' },
    ],
    mockupBg: 'bg-stone-200',
    url: 'http://thepiecraftmarketing.com/',
    image: '/projects/thepiecraft-marketing.jpg',
  },
  {
    id: 2,
    slug: 'thepiecraft-crm',
    name: 'ThePieCraft CRM',
    tag: 'Software',
    desc: 'A robust, custom-built CRM software tailored for digital agencies and creative studios.',
    bg: '#0a0a0a',
    accent: '#3b82f6',
    textColor: 'text-white',
    caseStudyTheme: 'dark',
    year: '2024',
    client: 'ThePieCraft Internal',
    services: ['SaaS Development', 'System Architecture', 'Dashboard UI'],
    challenge: 'Managing client lifecycles, project timelines, and invoicing across multiple disparate tools was creating operational bottlenecks and reducing creative bandwidth.',
    solution: 'We engineered a bespoke CRM system from the ground up, featuring real-time project tracking, automated invoicing, and a beautiful dark-mode first dashboard that our team actually loves using.',
    results: [
      { label: 'Adoption Rate', value: '100%' },
      { label: 'Time Saved', value: '10h/wk' },
      { label: 'Efficiency', value: '+40%' },
    ],
    mockupBg: 'bg-neutral-900',
    url: 'https://thepiecraft-crm.vercel.app/',
    image: '/projects/thepiecraft-crm.jpg',
  },
  {
    id: 3,
    slug: 'apex-watch',
    name: 'Apex Watch',
    tag: 'Web · E-commerce',
    desc: 'A premium, high-converting e-commerce storefront for luxury timepieces.',
    bg: '#171717',
    accent: '#f59e0b',
    textColor: 'text-amber-50',
    caseStudyTheme: 'dark',
    year: '2023',
    client: 'Apex Watches',
    services: ['E-commerce', 'Web Design', '3D Integration'],
    challenge: 'Apex needed an online storefront that matched the physical prestige of their luxury watches. Standard Shopify templates felt too cheap and constrained their brand identity.',
    solution: 'We designed a custom headless e-commerce experience with immersive product showcases, smooth transitions, and a highly optimized checkout flow that maximizes conversion rates without sacrificing aesthetics.',
    results: [
      { label: 'Bounce Rate', value: '-25%' },
      { label: 'Sales Lift', value: '+42%' },
      { label: 'Mobile Conv', value: '3.8%' },
    ],
    mockupBg: 'bg-zinc-900',
    url: 'https://apex-watch.vercel.app/',
    image: '/projects/apex-watch.jpg',
  },
  {
    id: 4,
    slug: 'yatrisync-web',
    name: 'YatriSync',
    tag: 'Web · App',
    desc: 'A modern digital platform for synchronizing travel itineraries and experiences.',
    bg: '#eff6ff',
    accent: '#2563eb',
    textColor: 'text-blue-950',
    caseStudyTheme: 'light',
    year: '2023',
    client: 'YatriSync',
    services: ['Web Application', 'UX Research', 'API Integration'],
    challenge: 'Travelers were struggling to consolidate bookings, flights, and hotel reservations into a single, easy-to-read itinerary that could be shared with friends and family.',
    solution: 'We built a progressive web app (PWA) that seamlessly syncs with email APIs to auto-generate beautiful, interactive travel itineraries that work flawlessly offline and across all devices.',
    results: [
      { label: 'Active Users', value: '50k+' },
      { label: 'Sync Time', value: '<2s' },
      { label: 'App Rating', value: '4.8' },
    ],
    mockupBg: 'bg-blue-50',
    url: 'http://yatrisync-web.vercel.app/',
    image: '/projects/yatrisync-web.jpg',
  },
  {
    id: 5,
    slug: 'thepiecraft-in',
    name: 'ThePieCraft India',
    tag: 'Web · Regional',
    desc: 'The dedicated regional hub for ThePieCraft’s operations and clients in India.',
    bg: '#fffbf0',
    accent: '#f97316',
    textColor: 'text-orange-950',
    caseStudyTheme: 'light',
    year: '2022',
    client: 'ThePieCraft',
    services: ['Localization', 'Web Design', 'SEO Strategy'],
    challenge: 'As our agency expanded globally, we needed a dedicated presence tailored to the Indian market to highlight regional case studies, team members, and localized contact information.',
    solution: 'We deployed a localized version of our core platform, optimized specifically for regional search engines and tailored to the cultural aesthetic and business needs of the Indian tech ecosystem.',
    results: [
      { label: 'Organic Traffic', value: '+120%' },
      { label: 'Lead Gen', value: '3x' },
      { label: 'Load Time', value: '0.8s' },
    ],
    mockupBg: 'bg-orange-50',
    url: 'http://thepiecraft.in/',
    image: '/projects/thepiecraft-in.jpg',
  },
];
