export interface Project {
  id: number;
  slug: string;
  name: string;
  tag: string;
  desc: string;
  bg: string;
  accent: string;
  textColor: string;
  caseStudyTheme: 'dark' | 'light';
  year: string;
  client: string;
  services: string[];
  challenge: string;
  solution: string;
  results: { label: string; value: string }[];
  mockupBg: string;
  url?: string;
  image: string;
  fullImage?: string;
}

export const PROJECTS: Project[] = [
  {
    id: 106,
    slug: 'theunknownband',
    name: 'The Unknown Band',
    tag: 'Web · Music',
    desc: 'An electrifying digital presence and acoustic concert landing page for The Unknown Band.',
    bg: '#000000',
    accent: '#10b981',
    textColor: 'text-zinc-100',
    caseStudyTheme: 'dark',
    year: '2023',
    client: 'The Unknown Band',
    services: ['Web Design', 'Audio Integration', 'Tour Management Setup'],
    challenge: 'The acoustic band needed a high-impact landing page to showcase their upcoming concerts, host their unreleased tracks, and sell merchandise directly to fans without relying solely on social media.',
    solution: 'We crafted a moody, high-energy acoustic band website featuring a custom audio player, immersive full-screen video backgrounds, and seamless event booking for live concerts.',
    results: [
      { label: 'Merch Sales', value: '+85%' },
      { label: 'Stream Clicks', value: '12k' },
      { label: 'Load Time', value: '1.2s' },
    ],
    mockupBg: 'bg-zinc-950',
    url: 'https://theunknownband.netlify.app/',
    image: '/projects/theunknownband-main.png',
    fullImage: '/projects/theunknownband-full.png',
  },
  {
    id: 105,
    slug: 'devshelter',
    name: 'DevShelter',
    tag: 'Web · Tooling',
    desc: 'Premium service apartments and aparthotels in Mumbai for corporate executives and travelers.',
    bg: '#0f172a',
    accent: '#8b5cf6',
    textColor: 'text-violet-100',
    caseStudyTheme: 'dark',
    year: '2023',
    client: 'DevShelter',
    services: ['Web App Development', 'Database Architecture', 'UI Design'],
    challenge: 'Business travelers and tourists often struggle with expensive hotel stays that lack the comfort of home. DevShelter needed a platform to showcase their luxurious, cost-effective service apartments.',
    solution: 'We built a lightning-fast React application highlighting premium aparthotels in Malad, Goregaon, and Jogeshwari, featuring advanced booking capabilities and a sleek, user-friendly interface.',
    results: [
      { label: 'Daily Active Users', value: '5k+' },
      { label: 'Search Speed', value: '<50ms' },
      { label: 'Community Submissions', value: '1.2k' },
    ],
    mockupBg: 'bg-zinc-950',
    url: 'https://devshelter.in/',
    image: '/projects/devshelter-main.png',
    fullImage: '/projects/devshelter-full.png',
  },
  {
    id: 103,
    slug: 'fragilebase',
    name: 'Fragilebase',
    tag: 'Web · Agency',
    desc: 'A premium e-commerce lifestyle brand specializing in sustainable, minimalist home essentials.',
    bg: '#0f172a',
    accent: '#3b82f6',
    textColor: 'text-blue-100',
    caseStudyTheme: 'dark',
    year: '2024',
    client: 'Fragilebase',
    services: ['Web Design', 'UI/UX', 'Frontend Development'],
    challenge: 'Fragile Base required an e-commerce platform that didn\'t just sell products, but framed their sustainable home essentials as art, requiring a delicate balance of performance and aesthetics.',
    solution: 'We engineered a highly optimized Shopify storefront with bespoke frontend integrations, ensuring fluid browsing, elegant product displays, and a frictionless checkout experience for lifestyle shoppers.',
    results: [
      { label: 'Engagement Time', value: '3m+' },
      { label: 'Bounce Rate', value: '<20%' },
      { label: 'Client Inquiries', value: '2x' },
    ],
    mockupBg: 'bg-zinc-950',
    url: 'https://fragilebase.com/',
    image: '/projects/fragilebase-main.png',
    fullImage: '/projects/fragilebase-full.png',
  },
  {
    id: 104,
    slug: 'apexgum',
    name: 'Apex Gum',
    tag: 'Web · E-commerce',
    desc: 'A high-performance Shopify storefront for a premium chewing gum brand focused on taste and coolness.',
    bg: '#18181b',
    accent: '#ef4444',
    textColor: 'text-red-50',
    caseStudyTheme: 'dark',
    year: '2024',
    client: 'Apex Gum',
    services: ['E-commerce', 'Brand Identity', 'Frontend Build'],
    challenge: 'Apex Gum needed an aggressively bold e-commerce experience to capture attention and sell their refreshing, long-lasting chewing gum to a highly active, trend-focused audience.',
    solution: 'We deployed a brutally fast Shopify storefront featuring bold typography, dark aesthetics, and rapid checkout flows to maximize sales and highlight the gum\'s unique coolness and taste.',
    results: [
      { label: 'Conversion Rate', value: '4.2%' },
      { label: 'Load Speed', value: '0.6s' },
      { label: 'Mobile Sales', value: '80%' },
    ],
    mockupBg: 'bg-zinc-950',
    url: 'https://apexgum.com/',
    image: '/projects/apexgum-main.png',
    fullImage: '/projects/apexgum-full.png',
  },
  {
    id: 101,
    slug: 'chaat-lounge',
    name: 'Chaat Lounge',
    tag: 'Web · Food & Beverage',
    desc: 'A vibrant digital experience for an authentic Mumbai street food and chaat restaurant brand.',
    bg: '#fdf2f8',
    accent: '#ec4899',
    textColor: 'text-pink-950',
    caseStudyTheme: 'light',
    year: '2024',
    client: 'Chaat Lounge',
    services: ['Web Design', 'Next.js Development', 'Menu Integration'],
    challenge: 'Since 2005, Chaat Lounge has served legendary Indian street food. They needed an online presence that matched their vibrant energy while making it incredibly easy to order Pani Puri and Pav Bhaji.',
    solution: 'We designed a fast-loading website using Next.js with rich food photography, vibrant color transitions, and an optimized mobile menu tailored for hungry customers seeking authentic Mumbai flavors.',
    results: [
      { label: 'Mobile Traffic', value: '75%' },
      { label: 'Menu Views', value: '+140%' },
      { label: 'Load Time', value: '<1s' },
    ],
    mockupBg: 'bg-zinc-950',
    url: 'https://chaat-lounge.vercel.app/',
    image: '/projects/chaatlounge-main.png',
    fullImage: '/projects/chaatlounge-full.png',
  },
  {
    id: 102,
    slug: 'mittron-icecream',
    name: 'Mittron Ice Cream',
    tag: 'Web · Retail',
    desc: 'A delightfully sweet brand showcase for an artisanal cafe serving natural, kothi-style ice cream.',
    bg: '#fefce8',
    accent: '#eab308',
    textColor: 'text-yellow-950',
    caseStudyTheme: 'light',
    year: '2024',
    client: 'Mittron Ice Cream',
    services: ['Brand Strategy', 'UI/UX Design', 'Web Development'],
    challenge: 'Mittron Ice Cream needed to communicate their commitment to 100% natural ingredients and traditional kothi-style preparation online to drive foot traffic to their cafes and boost local delivery orders.',
    solution: 'We built a delightful web experience featuring smooth, creamy animations, high-quality product photography of their natural ice creams, and seamless ordering integration to drive local cafe sales.',
    results: [
      { label: 'Online Orders', value: '+60%' },
      { label: 'Bounce Rate', value: '-22%' },
      { label: 'Brand Lift', value: 'High' },
    ],
    mockupBg: 'bg-zinc-950',
    url: 'https://mittron-icecream.vercel.app/',
    image: '/projects/mittron-main.png',
    fullImage: '/projects/mittron-full.png',
  },
  {
    id: 1,
    slug: 'thepiecraft-marketing',
    name: 'ThePieCraft Marketing',
    tag: 'Web · Brand',
    desc: 'India\'s premier restaurant performance marketing and Meta Ads agency for fine dining and luxury cafes.',
    bg: '#f0ece1',
    accent: '#000000',
    textColor: 'text-black',
    caseStudyTheme: 'light',
    year: '2024',
    client: 'ThePieCraft',
    services: ['Brand Strategy', 'UI/UX Design', 'Next.js Development'],
    challenge: 'As a rapidly growing marketing agency, ThePieCraft needed a website that reflected our high standard of design and technical excellence to attract premium hospitality clients and fine-dining venues.',
    solution: 'We built a highly aesthetic, SEO-optimized marketing website featuring smooth scroll mechanics, dynamic themes, and cinematic interactions to showcase our high-ROI Meta Ads and Google Ads campaigns.',
    results: [
      { label: 'Performance', value: '100' },
      { label: 'Load Time', value: '<1s' },
      { label: 'Conversion', value: '+35%' },
    ],
    mockupBg: 'bg-zinc-950',
    url: 'https://thepiecraftmarketing.com/',
    image: '/projects/thepiecraftmarketing-main.png',
    fullImage: '/projects/thepiecraftmarketing-full.png',
  },
  {
    id: 2,
    slug: 'thepiecraft-crm',
    name: 'ThePieCraft CRM',
    tag: 'Software',
    desc: 'A robust, automated CRM software tailored for digital agencies to handle projects, attendance, and clients.',
    bg: '#0a0a0a',
    accent: '#3b82f6',
    textColor: 'text-white',
    caseStudyTheme: 'dark',
    year: '2024',
    client: 'ThePieCraft Internal',
    services: ['SaaS Development', 'System Architecture', 'Dashboard UI'],
    challenge: 'Managing client lifecycles, team member attendance, project timelines, and invoicing across multiple tools was creating operational bottlenecks and reducing creative bandwidth for growing agencies.',
    solution: 'We engineered a bespoke CRM system from the ground up, automating project management and client tracking through a beautiful, easy-to-use dashboard that streamlines daily agency operations.',
    results: [
      { label: 'Adoption Rate', value: '100%' },
      { label: 'Time Saved', value: '10h/wk' },
      { label: 'Efficiency', value: '+40%' },
    ],
    mockupBg: 'bg-neutral-900',
    url: 'https://thepiecraft-crm.vercel.app/',
    image: '/projects/crm-main.png',
    fullImage: '/projects/crm-full.png',
  },
  {
    id: 3,
    slug: 'apex-watch',
    name: 'Apex Watch',
    tag: 'Web · E-commerce',
    desc: 'A lightning-fast, ad-free movie and series streaming application with no subscription required.',
    bg: '#171717',
    accent: '#f59e0b',
    textColor: 'text-amber-50',
    caseStudyTheme: 'dark',
    year: '2023',
    client: 'Apex Watches',
    services: ['E-commerce', 'Web Design', '3D Integration'],
    challenge: 'Users were frustrated by streaming platforms plagued with intrusive ads, hidden subscription fees, and clunky interfaces that ruined the movie and series viewing experience.',
    solution: 'We designed a custom streaming platform offering free, high-quality movies and series with zero ads and no subscriptions, featuring an incredibly intuitive UI and lightning-fast video playback.',
    results: [
      { label: 'Bounce Rate', value: '-25%' },
      { label: 'Sales Lift', value: '+42%' },
      { label: 'Mobile Conv', value: '3.8%' },
    ],
    mockupBg: 'bg-zinc-900',
    url: 'https://apex-watch.vercel.app/',
    image: '/projects/apexwatch-main.png',
    fullImage: '/projects/apexwatch-full.png',
  },
  {
    id: 4,
    slug: 'yatrisync-web',
    name: 'YatriSync',
    tag: 'Web · App',
    desc: 'A live group travel navigation app designed for synchronized bike trips and shared itineraries.',
    bg: '#eff6ff',
    accent: '#2563eb',
    textColor: 'text-blue-950',
    caseStudyTheme: 'light',
    year: '2023',
    client: 'YatriSync',
    services: ['Web Application', 'UX Research', 'API Integration'],
    challenge: 'During group bike trips, riders often use different maps and get separated, forcing the group to stop and wait if someone falls behind or takes a wrong turn.',
    solution: 'We built a live navigation app where a group leader sets the route and all members share live locations on a unified map, ensuring everyone stays connected and synchronized on the road.',
    results: [
      { label: 'Active Users', value: '50k+' },
      { label: 'Sync Time', value: '<2s' },
      { label: 'App Rating', value: '4.8' },
    ],
    mockupBg: 'bg-blue-50',
    url: 'https://yatrisync-web.vercel.app/',
    image: '/projects/yatrisync-main.png',
    fullImage: '/projects/yatrisync-full.png',
  },
  {
    id: 5,
    slug: 'thepiecraft-in',
    name: 'ThePieCraft India',
    tag: 'Web · Regional',
    desc: 'A premium online store for luxury handcrafted rugs, Persian carpets, and modern home decor.',
    bg: '#fffbf0',
    accent: '#f97316',
    textColor: 'text-orange-950',
    caseStudyTheme: 'light',
    year: '2022',
    client: 'ThePieCraft',
    services: ['Localization', 'Web Design', 'SEO Strategy'],
    challenge: 'ThePieCraft needed a luxurious e-commerce platform to showcase their artisan-crafted, 100% natural fiber rugs and carpets to an editorial Indian audience seeking high-end home decor.',
    solution: 'We deployed a localized, visually stunning online store optimized for high-ticket sales, featuring rich product imagery, seamless browsing, and an elegant aesthetic tailored to luxury rug buyers.',
    results: [
      { label: 'Organic Traffic', value: '+120%' },
      { label: 'Lead Gen', value: '3x' },
      { label: 'Load Time', value: '0.8s' },
    ],
    mockupBg: 'bg-orange-50',
    url: 'https://thepiecraft.in/',
    image: '/projects/thepiecraft-main.jpg',
    fullImage: '/projects/thepiecraft-full.png',
  },
];
